<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('t_users', function (Blueprint $table) {
            $table->id('pk_i_id');
            $table->string('s_name');
            $table->string('s_avatar')->nullable();
            $table->string('s_id_number')->nullable();
            $table->string('s_email')->nullable();
            $table->string('s_mobile')->unique();
            $table->string('s_mobile_whats');
            $table->string('s_password');
            $table->string('s_verify_code')->nullable();
            $table->boolean('b_email_verified')->default(0);
            $table->timestamp('sent_code_date')->nullable();
            $table->integer('b_enabled')->default(1);
            $table->boolean('b_enable_notification')->nullable()->default(true);
            $table->timestamp('dt_created_date')->nullable();
            $table->timestamp('dt_modified_date')->nullable();
            $table->timestamp('dt_deleted_date')->nullable();
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('t_users');
    }
}
